@startuml EsportareRubrica
actor Utente
participant "a MainController" as MC
participant "an ExportPopupController" as EPC

Utente -> MC ** : apre Rubrica
MC -> MC : Initialize(...)
activate MC
deactivate MC
Utente -> MC : clicca "Esporta"
activate MC
MC -> EPC ** : showExportPopup(...)
deactivate MC
EPC -> EPC : Initialize(...)
activate EPC
deactivate EPC
EPC -> EPC : choosePath(...)
activate EPC
Utente -> EPC : sceglie percorso del file
deactivate EPC
EPC -> EPC : genera file .csv o .vCard
activate EPC
deactivate EPC
Utente -> EPC : Clicca sul pulsante "Esporta"
EPC -> EPC : onExport(...)
activate EPC
alt utente ha scelto .csv
EPC -> EPC : onExportCSV(...)
activate EPC
deactivate EPC
else utente ha scelto .vCard
EPC -> EPC : onExportVCard(...)
activate EPC
deactivate EPC
end
EPC -> EPC : salva file
destroy EPC
deactivate EPC
@enduml