@startuml EliminareModificareContatto

actor Utente as u
participant "a MainController" as mc 
participant "an AddressBook" as ab 
participant "a Contact" as c

u -> mc ** : Apre rubrica
activate mc 
mc -> mc : Initialize(...)
mc -> ab ** : getInstance()
loop Utente digita nel TextField searchField una sottostringa o sceglie un tag
    u -> mc : Digita una sottostringa nella barra di ricerca
    mc -> mc : searchFieldBinding()
    mc --> u : Restituisce i contatti che rispecchiano i criteri di ricerca
    break Quando l'utente clicca su un contatto
        u -> mc : clicca su un contatto
        mc -> mc : onContactclicked(MouseEvent event)
        deactivate "a Contact"
    end
end
deactivate mc

alt "Utente clicca Annulla"
    u -> mc : L'utente clicca sul pulsante "Annulla"
    mc -> mc : onCancelContact(ActionEvent event)

else utente clicca su "Elimina"
u -> mc : utente clicca su "Elimina"
activate mc
mc -> mc : onRemoveContact(...)
mc -> u : mostra la schermata di conferma
u -> mc : conferma l'operazione
mc -> ab : removeContact(Contact c)
deactivate mc

else utente clicca su "Modifica"
u -> mc : utente clicca su "Modifica"
activate mc
mc -> mc : onModifyContact(...)
mc -> u : rende modificabili i campi
u -> mc : modifica qualsiasi campo
u -> mc : clicca "Salva"
mc -> c ** : modifica il contatto
deactivate mc

end

@enduml