@startuml Aggiunta Database
actor Utente as u
participant "a MainController" as mc
participant "a ConfigPopupController" as cpc
participant "a AddressBook" as ab
participant "Database" as sd
participant "a Database" as d

u -> mc : nel menù file clicca "Config"
activate mc
mc -> cpc ** : showConfigPopup()
deactivate mc
u -> cpc : inserisce URL del database e clicca "Verifica"
cpc -> cpc : onVerify()
activate cpc
cpc -> sd : verifyDBUrl(String url)
note right
    Questo metodo è statico.
end note
activate cpc
activate sd
sd --> cpc : boolean
deactivate sd
deactivate cpc
deactivate cpc
alt "L'url è valido"
    u -> cpc : clicca "Conferma"
    cpc -> cpc : onConfirm()
    activate cpc
    cpc -> ab : setDBUrl(String url)
    activate ab
    deactivate ab
    cpc -> ab : saveConfig()
    activate ab
    deactivate ab
    cpc -> ab : initDB()
    activate ab
    ab -> d ** : Database(String url)

    ab -\\ d : insertManyContacts(...)
    activate d
    deactivate d

    ab -\\ d : insertManyTags(...)
    activate d
    deactivate d

    ab -> ab : removeOBJ()
    activate ab
    deactivate ab
    note left
    Rimuove Data.bin
    end note

    deactivate ab
    deactivate cpc
    destroy cpc
end
@enduml