@startuml DiagrammaDelleClassi
skinparam linetype ortho
'left to right direction

class Contact {
    - String name 
    - String surname 
    - String[] numbers
    - String[] emails
    - byte[] profilePicture
    - Set<String> tags

    + Contact(String name, String surname)
    + String getName()
    + void setName(String name)
    + String getSurname()
    + void setSurname(String surname)
    + String[] getNumbers()
    + void setNumbers(String[] numbers)
    + String[] getEmails()
    + void setEmails(String[] emails)
    + byte[] getProfilePicture()
    + void setProfilePicture(byte[] profilePicture)
    + Set<String> getTags()
    + void setTags(Set<String> tags)
    + boolean equals(Object o)
    
}

interface MongoSerializable {
    +void toDocument() 
    +void fromDocument()
}

Contact ..|> MongoSerializable

class AddressBook {
    - ObservableList<Contact> contacts
    - ObservableSet<String> tags
    - static AddressBook instance
    - String dbUrl 

    - AddressBook()
    + ObservableList<Contact> getContacts()
    + void addContact(Contact c)
    + Contact removeContact(Contact c)
    + ObservableSet<String> getTags()
    + void addTag(String tag)
    + String removeTag(String tag)
    + static AddressBook getInstance()
    + void setDbUrl(String dbUrl)
    + String getDbUrl()    
    + void saveConfig()
    + void loadConfig()
    + void saveOBJ()
    + AddressBook loadOBJ()
    + void saveToDB()
    + AddressBook loadFromDB()
    
}

interface Serializable
Contact ..|> Serializable
AddressBook "1" o-- "0..*" Contact

class MainController {
    - AddressBook addressBook
    - Button deleteButton
    - Button saveButton
    - Button editButton
    - Button cancelButton
    - VBox tagVBox
    - VBox lettersVBox
    - TextField searchField
    - TextField nameField
    - TextField surnameField
    - TextField emailField
    - TextField numberField
    - ImageView profileImageView
    - ImageView filterImage
    - TableView<Contact> contactsTable
    - TableColumn<Contact,String> nameColumn
    - TableColumn<Contact,String> surnameColumn
    - AnchorPane contactDetailsPane
    - GridPane numbersPane
    - GridPane emailsPane
    - ContextMenu contextMenu

    + void initialize(URL location, ResourceBundle resources)
    - void setImageCircle()
    - void searchFieldBinding()    
    - void onFilterClicked()
    - void onAddButtonPressed(ActionEvent event)
    - void onContactClicked(MouseEvent event)
    - void onSaveContact(ActionEvent event)
    - void onModifyContact(ActionEvent event)
    - void onRemoveContact(ActionEvent event)
    - void onCancelContact(ActionEvent event)
    - void showImportPopup(ActionEvent event)
    - void showExportPopup(ActionEvent event)
    - void showConfigPopup(ActionEvent event)
    - void showImagePopup(ActionEvent event)
    - void showManageTagsPopup(ActionEvent event)
}

MainController ..> ImagePopupController


interface Initializable
MainController ..|> Initializable
MainController "1" o-- "1" AddressBook

class ImportPopupController {
    - AddressBook addressBook
    - Button importButton
    + void initialize(URL location, ResourceBundle resources)
    - void selectFile(ActionEvent event)
    - void onImport(ActionEvent event)
    - boolean checkCSVFormat()
    - boolean checkVCardFormat()
}

ImportPopupController ..|> Initializable
ImportPopupController "1" o-- "1" AddressBook

class ExportPopupController {
    - AddressBook addressBook
    - ChoiceBox<String> exportChoiceBox
    - RadioButton vCardButton
    - RadioButton csvButton
    - ToggleGroup ext
    - Button saveButton

    + void initialize(URL location, ResourceBundle resources)
    - void choosePath(ActionEvent event)
    - void onExport()
}

ExportPopupController ..|> Initializable
ExportPopupController "1" o-- "1" AddressBook

class ManageTagsPopupController {
    - AddressBook addressBook
    - Button addButton
    - Button updateButton
    - Button deleteButton

    + void initialize(URL location, ResourceBundle resources)
    - void onAdd(ActionEvent event)
    - void onUpdate(ActionEvent event)
    - void onDelete(ActionEvent event)
}

ManageTagsPopupController ..|> Initializable
ManageTagsPopupController "1" o-- "1" AddressBook

class ImagePopupController {
    - ImageView imgAdd
    - HBox defaultImgHBox
    - File selectedImage
    - int imageIndex

    + void initialize(URL location, ResourceBundle resources)
    - void onImageAdd(MouseEvent event)
    + File getSelectedImage()
    + int getImageIndex()
}
ImagePopupController ..|> Initializable

class ConfirmPopupController {
    - onConfirm()
    - onCancel()
}
MainController ..> ConfirmPopupController
ManageTagsPopupController ..> ConfirmPopupController

@enduml