@startuml
actor Utente
participant "a MainController" as MC
participant "a AddressBook" as R

Utente -> MC ** : apre Rubrica
activate MC
MC -> MC : Initialize(...)
deactivate MC
Utente -> MC : effettua una modifica
activate MC
MC -> R : salvaOBJ()
deactivate MC
activate R
R -> R : Salvataggio in Data.bin
deactivate R
@enduml