@startuml AggiungereContatto

actor Utente as u  
participant "a MainController" as mc 
participant "an AddressBook" as ab 
participant "ImagePopupController" as ipc
participant "a Contact" as c

u -> mc ** : Apre rubrica
activate mc 
mc -> mc : Initialize(...)
mc -> ab ** : getInstance()
deactivate mc

u -> mc :  clicca "+" o "Aggiungi contatto"
activate mc 
mc -> mc : onAddButtonPressed(...)
mc --> u : mostra schermata di aggiunta contatto
u -> mc : inserisce i campi del contatto

alt utente clicca sull'immagine
u -> mc : clicca sull'immagine
activate mc
mc -> ipc ** : showImagePopup(...)
deactivate mc
u -> ipc : sceglie un'immagine
activate ipc
ipc -> ipc : carica un'immagine
mc -> ipc : getSelectedImage()
destroy ipc
end

u -> mc : clicca "Salva"
mc -> mc : onSaveContact(...)
mc -> c ** : crea il contatto
mc -> ab : addContact(Contact c)

@enduml