@startuml EsportareRubrica
actor Utente
participant "a MainController" as MC
participant "an ExportPopupController" as EPC

Utente -> MC ** : apre Rubrica
activate MC
MC -> MC : Initialize(...)
deactivate MC
Utente -> MC : clicca "Esporta"
activate MC
MC -> EPC ** : showExportPopup(...)
deactivate MC
activate EPC
EPC -> EPC : Initialize(...)
EPC -> EPC : choosePath(...)
Utente -> EPC : sceglie percorso
EPC -> EPC : genera file .csv o .vCard
Utente -> EPC : Clicca sul pulsante "Esporta"
EPC -> EPC : onExportButtonPressed(ActionEvent event)
EPC -> EPC : salva file
destroy EPC
@enduml