@startuml EliminareModificareContatto

actor Utente as u
participant "a MainController" as mc 
participant "an AddressBook" as ab 
participant "a Contact" as c

u -> mc ** : Apre rubrica
mc -> mc : Initialize(...)
activate mc 
mc -> ab ** : getInstance()
activate ab
ab --> mc : lista dei contatti
deactivate ab
mc --> u : mostra la lista dei contatti
deactivate
loop Utente digita nel TextField searchField una sottostringa o sceglie un tag
    u -> mc : Digita una sottostringa nella barra di ricerca
    mc -> mc : searchFieldBinding()
    activate mc
    mc --> u : Restituisce i contatti che rispecchiano i criteri di ricerca
    deactivate mc
    break Quando l'utente clicca su un contatto
        u -> mc : clicca su un contatto
        mc -> mc : onContactclicked(MouseEvent event)
        activate mc
        deactivate mc

end
end
deactivate mc

alt utente clicca su "Elimina"
u -> mc : utente clicca su "Elimina"
mc -> mc : onRemoveContact(...)
activate mc
mc -> u : mostra la schermata di conferma
u -> mc : conferma l'operazione
mc -> ab : removeContact(Contact c)
deactivate mc

else utente clicca su "Modifica"
u -> mc : utente clicca su "Modifica"
mc -> mc : onModifyContact(...)
activate mc
mc -> u : rende modificabili i campi
u -> mc : modifica qualsiasi campo
u -> mc : clicca "Salva"
mc -> c ** : modifica il contatto
deactivate mc

end

@enduml