@startuml Salvataggio in locale o in DB

actor Utente as u
'participant "a MainController" as mc
participant "a AddressBook" as ab
participant "a Database" as d

u -> ab : aggiunge/modifica/elimina contatto o tag

ab -> ab : metodo di modifica rubrica
note right
ad esempio
addContact(...)
removeTag(...)
end note
activate ab

alt non esiste un DB per il salvataggio
ab -> ab : saveOBJ()
activate ab
ab -> ab : Salvataggio lista contatti in Data.bin
activate ab
deactivate ab
ab -> ab : Salvataggio lista tags in Data.bin
activate ab
deactivate ab
deactivate ab

else esiste un DB per il salvataggio
ab -\\ d : metodo aggiornamento 
activate ab
note right
ad esempio
upsertContact(...)
removeTag(...)
end note
activate d
deactivate d
deactivate ab
deactivate ab

end

@enduml